name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y fping
    - name: Test program
      run: |
        python nordvpn_best.py -h
        python nordvpn_best.py --debug 'Sydney, AU'
        python nordvpn_best.py --debug 'US' --load 15
        python nordvpn_best.py --debug 'AU' --load 10 --fping
        python nordvpn_best.py --debug 'Sydney, AU' --show-mbps
